let park = [
    {
        id: 1,
        name: "Luna",
        species: "Steinbock",
        gender: "f",
        age: 10,
        enclosure: "Alpenkamm",
        friends: [2],
        children_count: 1,
        pregnant: false,
        diet: "pflanzlich",
        region: "CH"
    },
    {
        id: 2,
        name: "Alpin",
        species: "Steinbock",
        gender: "m",
        age: 12,
        enclosure: "Alpenkamm",
        friends: [1],
        children_count: 0,
        diet: "pflanzlich",
        region: "CH"
    },
    {
        id: 3,
        name: "Falk",
        species: "Fuchs",
        gender: "m",
        age: 4,
        enclosure: "Waldlichtung",
        friends: [11],
        children_count: 0,
        diet: "allesfresser",
        region: "DE"
    },
    {
        id: 4,
        name: "Runa",
        species: "Luchs",
        gender: "f",
        age: 7,
        enclosure: "Felsenhang",
        friends: [3],
        children_count: 1,
        pregnant: true,
        diet: "fleischfresser",
        region: "AT"
    },
    {
        id: 5,
        name: "Balu",
        species: "Braunbär",
        gender: "m",
        age: 14,
        enclosure: "Bergwald",
        friends: [6],
        children_count: 2,
        diet: "allesfresser",
        region: "DE"
    },
    {
        id: 6,
        name: "Mila",
        species: "Murmeltier",
        gender: "f",
        age: 3,
        enclosure: "Bergwiese",
        friends: [5,10],
        children_count: 0,
        pregnant: false,
        diet: "pflanzlich",
        region: "CH"
    },
    {
        id: 7,
        name: "Wanda",
        species: "Wisent",
        gender: "f",
        age: 8,
        enclosure: "Weide",
        friends: [8],
        children_count: 1,
        pregnant: false,
        diet: "pflanzlich",
        region: "DE"
    },
    {
        id: 8,
        name: "Roco",
        species: "Wisent",
        gender: "m",
        age: 9,
        enclosure: "Weide",
        friends: [7],
        children_count: 1,
        diet: "pflanzlich",
        region: "DE"
    },
    {
        id: 9,
        name: "Dachs",
        species: "Dachs",
        gender: "m", age: 6,
        enclosure: "Waldlichtung",
        friends: [3],
        children_count: 0,
        diet: "allesfresser",
        region: "AT"
    },
    {
        id: 10,
        name: "Zora",
        species: "Reh",
        gender: "f",
        age: 5,
        enclosure: "Waldsaum",
        friends: [6],
        children_count: 1,
        pregnant: true,
        diet: "pflanzlich",
        region: "AT"
    },
    {
        id: 11,
        name: "Arno",
        species: "Wolf",
        gender: "m",
        age: 5,
        enclosure: "Felsenhang",
        friends: [3,4],
        children_count: 0,
        diet: "fleischfresser",
        region: "DE"
    },
    {
        id: 12,
        name: "Greta",
        species: "Auerhuhn",
        gender: "f",
        age: 4,
        enclosure: "Bergwiese",
        friends: [],
        children_count: 0,
        pregnant: false,
        diet: "pflanzlich",
        region: "CH"
    },
];
console.log(park);
